# Generated by Django 6.0.6 on 2026-08-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiomaextrangero',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/produccion'),
        ),
        migrations.AddField(
            model_name='idiomaextrangero',
            name='nit_empresa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
