# Generated by Django 5.2.11 on 2026-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='ciudad_obtencion_certificado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='departamento_obtencion_certificado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='fecha_obtecion_certificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='institucion_expedicion_certificado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='nevel_certificado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='pais_obtencion_certificado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
