# Generated by Django 6.0.6 on 2026-06-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0002_alter_idiomaextrangero_ciudad_obtencion_certificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienciaslaborale',
            options={'ordering': ['-fecha_inicio']},
        ),
    ]
