# Generated by Django 6.0.6 on 2026-08-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0002_idiomaextrangero_cargar_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncientifica',
            name='nit_empresa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
