# Generated by Django 6.0.6 on 2026-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0003_alter_experienciaslaborale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaslaborale',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
