# Generated by Django 6.0.6 on 2026-08-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0003_participacioncientifica_nit_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiomaextrangero',
            name='tipo_idioma',
        ),
        migrations.AlterField(
            model_name='idiomaextrangero',
            name='nit_empresa',
            field=models.CharField(max_length=20),
        ),
    ]
