# Generated by Django 6.0.6 on 2026-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0004_experienciaslaborale_acronimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulosacademico',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
