# Generated by Django 6.0.6 on 2026-08-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0004_remove_idiomaextrangero_tipo_idioma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomaextrangero',
            options={'ordering': ['id']},
        ),
    ]
