# Generated by Django 6.0.6 on 2026-08-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0005_alter_idiomaextrangero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomaextrangero',
            options={},
        ),
        migrations.AddField(
            model_name='idiomaextrangero',
            name='tipo_idioma',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
