# Generated by Django 6.0.6 on 2026-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0005_titulosacademico_acronimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulosacademico',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.AddField(
            model_name='fotospersonale',
            name='imagen_de_portada',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/foto'),
        ),
    ]
