# Generated by Django 6.0.6 on 2026-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0006_alter_idiomaextrangero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonale',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
