# Generated by Django 6.0.6 on 2026-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0006_alter_titulosacademico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotospersonale',
            name='imagen_panel_izquierdo',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/foto'),
        ),
    ]
