# Generated by Django 6.0.6 on 2026-08-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0007_datospersonale_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonale',
            old_name='linkedin',
            new_name='linkedIn',
        ),
    ]
