# Generated by Django 6.0.6 on 2026-06-30 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0007_fotospersonale_imagen_panel_izquierdo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosImpartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_disciplina', models.CharField(max_length=10)),
                ('nombre_disciplina', models.CharField(max_length=30)),
                ('tematicas_disciplina', models.CharField(max_length=1000)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
