# Generated by Django 6.0.6 on 2026-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0008_cursosimpartidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosimpartidos',
            name='autor_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='link_bibliografia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='titulo_documento_guia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
