# Generated by Django 6.0.6 on 2026-07-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0010_remove_cursosimpartidos_unidades_de_tematica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='tematicas_disciplina',
        ),
    ]
