# Generated by Django 6.0.6 on 2026-07-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0011_remove_unidadescursosimpartidos_tematicas_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='tematicas_disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos'),
            preserve_default=False,
        ),
    ]
