# Generated by Django 6.0.6 on 2026-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0012_unidadescursosimpartidos_tematicas_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosimpartidos',
            name='titulo_material_ayuda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='url_material_ayuda',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UnidadesCursosImpartidos',
        ),
    ]
