# Generated by Django 6.0.6 on 2026-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0013_cursosimpartidos_titulo_material_ayuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosimpartidos',
            name='tematica_curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
