# Generated by Django 6.0.6 on 2026-07-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0014_cursosimpartidos_tematica_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='titulo_material_ayuda',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='unidades_de_tematica',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='url_material_ayuda',
        ),
        migrations.CreateModel(
            name='UnidadesCursosImpartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_de_tematica', models.CharField(blank=True, max_length=2000, null=True)),
                ('titulo_material_ayuda', models.CharField(blank=True, max_length=100, null=True)),
                ('url_material_ayuda', models.URLField(blank=True, null=True)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tematicas_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos')),
            ],
        ),
    ]
