# Generated by Django 6.0.6 on 2026-07-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0015_remove_cursosimpartidos_titulo_material_ayuda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='tematicas_disciplina',
        ),
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='nombre_usuario',
        ),
    ]
