# Generated by Django 6.0.6 on 2026-07-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0016_remove_cursosimpartidos_tematicas_disciplina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosimpartidos',
            old_name='tematica_curso',
            new_name='tematicas_del_curso',
        ),
    ]
