# Generated by Django 6.0.6 on 2026-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0017_rename_tematica_curso_cursosimpartidos_tematicas_del_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosimpartidos',
            name='tematicas_del_curso',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
