# Generated by Django 6.0.6 on 2026-07-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0018_alter_cursosimpartidos_tematicas_del_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadescursosimpartidos',
            old_name='tematicas_disciplina',
            new_name='disciplina_o_curso',
        ),
    ]
