# Generated by Django 6.0.6 on 2026-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0019_rename_tematicas_disciplina_unidadescursosimpartidos_disciplina_o_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosimpartidos',
            old_name='tematicas_del_curso',
            new_name='conjunto_tematicas',
        ),
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='tematicas',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
