# Generated by Django 6.0.6 on 2026-07-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0020_rename_tematicas_del_curso_cursosimpartidos_conjunto_tematicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='tematicas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
