# Generated by Django 6.0.6 on 2026-07-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0024_alter_unidadescursosimpartidos_nombre_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosimpartidos',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unidadescursosimpartidos',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='autor_documento',
        ),
        migrations.AlterField(
            model_name='cursosimpartidos',
            name='titulo_documento_guia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
