# Generated by Django 6.0.6 on 2026-07-13 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0025_alter_cursosimpartidos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='link_bibliografia',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='titulo_documento_guia',
        ),
        migrations.CreateModel(
            name='CitasBibliograficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_documento_guia', models.CharField(blank=True, max_length=500, null=True)),
                ('link_bibliografia', models.URLField(blank=True, null=True)),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
