# Generated by Django 6.0.6 on 2026-07-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0026_remove_cursosimpartidos_link_bibliografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='nombre_usuario',
        ),
    ]
