# Generated by Django 6.0.6 on 2026-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0028_citasbibliograficas_nombre_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasbibliograficas',
            old_name='codigo_curso',
            new_name='identificador_disciplina',
        ),
    ]
