# Generated by Django 6.0.6 on 2026-07-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0029_rename_codigo_curso_citasbibliograficas_identificador_disciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasbibliograficas',
            old_name='identificador_disciplina',
            new_name='codigo_curso',
        ),
    ]
