# Generated by Django 6.0.6 on 2026-07-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0030_rename_identificador_disciplina_citasbibliograficas_codigo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasbibliograficas',
            name='codigo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos'),
        ),
    ]
