# Generated by Django 6.0.6 on 2026-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0031_alter_citasbibliograficas_codigo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasbibliograficas',
            name='codigo_curso',
            field=models.CharField(max_length=100),
        ),
    ]
