# Generated by Django 6.0.6 on 2026-07-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0032_alter_citasbibliograficas_codigo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasbibliograficas',
            name='nombre_curso',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
