# Generated by Django 6.0.6 on 2026-07-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0033_citasbibliograficas_nombre_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='relacion_bilbiografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hojadevida.citasbibliograficas'),
        ),
    ]
