# Generated by Django 6.0.6 on 2026-07-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0034_unidadescursosimpartidos_relacion_bilbiografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasbibliograficas',
            name='key_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos'),
        ),
    ]
