# Generated by Django 6.0.6 on 2026-07-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0035_citasbibliograficas_key_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasbibliograficas',
            name='key_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos'),
        ),
    ]
