# Generated by Django 6.0.6 on 2026-07-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0036_alter_citasbibliograficas_key_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='key_curso',
        ),
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='relacion_bilbiografica',
        ),
    ]
