# Generated by Django 6.0.6 on 2026-07-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0037_remove_citasbibliograficas_key_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasbibliograficas',
            name='tipo_texto_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
