# Generated by Django 6.0.6 on 2026-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0038_citasbibliograficas_tipo_texto_guia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citasbibliograficas',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='citasbibliograficas',
            name='capitulos_texto',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
