# Generated by Django 6.0.6 on 2026-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0039_alter_citasbibliograficas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='tematicas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
