# Generated by Django 6.0.6 on 2026-07-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0040_alter_unidadescursosimpartidos_tematicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='numero_unidad',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
