# Generated by Django 6.0.6 on 2026-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0041_unidadescursosimpartidos_numero_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciastecnicascomputacionale',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='datospersonale',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='experienciaslaborale',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='participacioncientifica',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='titulosacademico',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
    ]
