# Generated by Django 6.0.6 on 2026-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0042_competenciastecnicascomputacionale_cargar_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciastecnicascomputacionale',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participacioncientifica',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
