# Generated by Django 6.0.6 on 2026-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0043_competenciastecnicascomputacionale_acronimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenciastecnicascomputacionale',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='competenciastecnicascomputacionale',
            name='acronimo',
        ),
        migrations.AddField(
            model_name='datospersonale',
            name='afiliacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='datospersonale',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
