# Generated by Django 6.0.6 on 2026-07-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0044_alter_competenciastecnicascomputacionale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccionacademica',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='datospersonale',
            name='cargar_icono',
        ),
    ]
