# Generated by Django 6.0.6 on 2026-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0045_alter_produccionacademica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionacademica',
            name='documento_soporte',
            field=models.FileField(blank=True, null=True, upload_to='files/docs/papers'),
        ),
    ]
