# Generated by Django 6.0.6 on 2026-07-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0046_produccionacademica_documento_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaslaborale',
            name='acronimo',
        ),
        migrations.RemoveField(
            model_name='participacioncientifica',
            name='acronimo',
        ),
        migrations.RemoveField(
            model_name='produccionacademica',
            name='acronimo',
        ),
        migrations.RemoveField(
            model_name='titulosacademico',
            name='acronimo',
        ),
    ]
