# Generated by Django 6.0.6 on 2026-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0047_remove_experienciaslaborale_acronimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciastecnicascomputacionale',
            name='documento_soporte',
            field=models.FileField(null=True, upload_to='files/docs/certificados'),
        ),
    ]
