# Generated by Django 6.0.6 on 2026-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0048_alter_competenciastecnicascomputacionale_documento_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciastecnicascomputacionale',
            name='documento_soporte',
            field=models.FileField(blank=True, null=True, upload_to='files/docs/certificados'),
        ),
    ]
