# Generated by Django 6.0.6 on 2026-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0049_alter_competenciastecnicascomputacionale_documento_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciastecnicascomputacionale',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='experienciaslaborale',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='idiomaextrangero',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participacioncientifica',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='titulosacademico',
            name='imprimir_datos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
