# Generated by Django 6.0.6 on 2026-07-24 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0050_competenciastecnicascomputacionale_imprimir_datos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenciastecnicascomputacionale',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='experienciaslaborale',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='idiomaextrangero',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='participacioncientifica',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='produccionacademica',
            name='imprimir_datos',
        ),
        migrations.RemoveField(
            model_name='titulosacademico',
            name='imprimir_datos',
        ),
        migrations.CreateModel(
            name='ImprimirHojaDeVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprimir_estudio', models.CharField(blank=True, max_length=10, null=True)),
                ('imprimir_experiencia', models.CharField(blank=True, max_length=10, null=True)),
                ('imprimir_idioma', models.CharField(blank=True, max_length=10, null=True)),
                ('imprimir_produccion', models.CharField(blank=True, max_length=10, null=True)),
                ('imprimir_participacion', models.CharField(blank=True, max_length=10, null=True)),
                ('imprimir_tecnicas', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
