# Generated by Django 6.0.6 on 2026-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0051_remove_competenciastecnicascomputacionale_imprimir_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprimirhojadevida',
            name='imprimir_perfil',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
