# Generated by Django 6.0.6 on 2026-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0052_imprimirhojadevida_imprimir_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_estudio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_experiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_idioma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_participacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_produccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imprimirhojadevida',
            name='imprimir_tecnicas',
            field=models.BooleanField(default=False),
        ),
    ]
