# Generated by Django 6.0.6 on 2026-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0053_alter_imprimirhojadevida_imprimir_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprimirhojadevida',
            name='imprimir_documentacion',
            field=models.BooleanField(default=False),
        ),
    ]
