# Generated by Django 6.0.6 on 2026-07-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0054_imprimirhojadevida_imprimir_documentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccionacademica',
            old_name='nombre_trabajo',
            new_name='grado_academico',
        ),
    ]
