# Generated by Django 6.0.6 on 2026-07-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0055_rename_nombre_trabajo_produccionacademica_grado_academico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccionacademica',
            old_name='grado_academico',
            new_name='nombre_trabajo',
        ),
    ]
