# Generated by Django 6.0.6 on 2026-07-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0056_rename_grado_academico_produccionacademica_nombre_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionacademica',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='intereses_investigativos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
