# Generated by Django 6.0.6 on 2026-07-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0057_produccionacademica_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionacademica',
            name='area_concentracion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='doi_link_publicacion',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='nombre_revista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='nombre_trabajo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='pais_publicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
