# Generated by Django 6.0.6 on 2026-07-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0058_alter_produccionacademica_area_concentracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionacademica',
            name='mostrar_producto',
            field=models.BooleanField(default=False),
        ),
    ]
