# Generated by Django 6.0.6 on 2026-07-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0060_alter_produccionacademica_mostrar_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionacademica',
            name='mostrar_producto',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
