# Generated by Django 6.0.6 on 2026-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0061_alter_produccionacademica_mostrar_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionacademica',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
