# Generated by Django 6.0.6 on 2026-07-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0062_alter_produccionacademica_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionacademica',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
