# Generated by Django 6.0.6 on 2026-07-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0063_alter_produccionacademica_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccionacademica',
            old_name='intereses_investigativos',
            new_name='tipos_de_productos',
        ),
    ]
