# Generated by Django 6.0.6 on 2026-07-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0064_rename_intereses_investigativos_produccionacademica_tipos_de_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionacademica',
            name='tecnologias_utilizadas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
