# Generated by Django 6.0.6 on 2026-07-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0065_produccionacademica_tecnologias_utilizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaslaborale',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='titulosacademico',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
