# Generated by Django 6.0.6 on 2026-07-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0066_experienciaslaborale_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionacademica',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
