# Generated by Django 6.0.6 on 2026-07-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0067_alter_produccionacademica_palabras_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasbibliograficas',
            name='numero_unidad',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='citasbibliograficas',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='UnidadesCursosImpartidos',
        ),
    ]
