# Generated by Django 6.0.6 on 2026-07-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0068_citasbibliograficas_numero_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='numero_unidad',
        ),
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='unidades_de_tematica',
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='numero_unidad',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
