# Generated by Django 6.0.6 on 2026-07-28 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0069_remove_citasbibliograficas_numero_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='numero_unidad',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='unidades_de_tematica',
        ),
        migrations.CreateModel(
            name='UnidadesCursosImpartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematicas', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_material_ayuda', models.CharField(blank=True, max_length=100, null=True)),
                ('url_material_ayuda', models.URLField(blank=True, null=True)),
                ('unidades_de_tematica', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero_unidad', models.CharField(blank=True, max_length=3)),
                ('disciplina_o_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.cursosimpartidos')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
