# Generated by Django 6.0.6 on 2026-07-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0070_remove_cursosimpartidos_numero_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosimpartidos',
            name='conjunto_tematicas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
