# Generated by Django 6.0.6 on 2026-07-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0071_alter_cursosimpartidos_conjunto_tematicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='conjunto_tematicas',
        ),
    ]
