# Generated by Django 6.0.6 on 2026-07-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0072_remove_cursosimpartidos_conjunto_tematicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='titulo_material_ayuda',
        ),
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='url_material_ayuda',
        ),
    ]
