# Generated by Django 6.0.6 on 2026-07-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0073_remove_unidadescursosimpartidos_titulo_material_ayuda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadescursosimpartidos',
            options={'ordering': ['numero_unidad']},
        ),
    ]
