# Generated by Django 6.0.6 on 2026-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0074_alter_unidadescursosimpartidos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='numero_unidad',
            field=models.IntegerField(blank=True, max_length=3),
        ),
    ]
