# Generated by Django 6.0.6 on 2026-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0075_alter_unidadescursosimpartidos_numero_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaslaborale',
            name='acronimo_universidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='unidades_de_tematica',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
