# Generated by Django 6.0.6 on 2026-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0076_experienciaslaborale_acronimo_universidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaslaborale',
            name='acronimo_universidad',
        ),
        migrations.AddField(
            model_name='experienciaslaborale',
            name='nit_empresa',
            field=models.IntegerField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
