# Generated by Django 6.0.6 on 2026-07-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0077_remove_experienciaslaborale_acronimo_universidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaslaborale',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
