# Generated by Django 6.0.6 on 2026-07-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0078_alter_experienciaslaborale_nit_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='numero_unidad',
            field=models.IntegerField(blank=True),
        ),
    ]
