# Generated by Django 6.0.6 on 2026-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0079_alter_unidadescursosimpartidos_numero_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaslaborale',
            name='nit_empresa',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
