# Generated by Django 6.0.6 on 2026-07-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0080_alter_experienciaslaborale_nit_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasbibliograficas',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='citasbibliograficas',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='competenciastecnicascomputacionale',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='cursosimpartidos',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='idiomaextrangero',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='idiomaextrangero',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imprimirhojadevida',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='imprimirhojadevida',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='participacioncientifica',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='produccionacademica',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='titulosacademico',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome'),
        ),
        migrations.AddField(
            model_name='unidadescursosimpartidos',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
