# Generated by Django 6.0.6 on 2026-07-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0081_citasbibliograficas_cargar_icono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='cargar_icono',
        ),
        migrations.RemoveField(
            model_name='citasbibliograficas',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='competenciastecnicascomputacionale',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='cargar_icono',
        ),
        migrations.RemoveField(
            model_name='cursosimpartidos',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='idiomaextrangero',
            name='cargar_icono',
        ),
        migrations.RemoveField(
            model_name='idiomaextrangero',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='imprimirhojadevida',
            name='cargar_icono',
        ),
        migrations.RemoveField(
            model_name='imprimirhojadevida',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='participacioncientifica',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='produccionacademica',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='titulosacademico',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='cargar_icono',
        ),
        migrations.RemoveField(
            model_name='unidadescursosimpartidos',
            name='nit_empresa',
        ),
        migrations.AlterField(
            model_name='experienciaslaborale',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='numero_unidad',
            field=models.IntegerField(blank=True, max_length=3),
        ),
    ]
