# Generated by Django 6.0.6 on 2026-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0082_remove_citasbibliograficas_cargar_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulosacademico',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
