# Generated by Django 6.0.6 on 2026-07-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0083_titulosacademico_nit_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionacademica',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='competenciastecnicascomputacionale',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/competencia'),
        ),
        migrations.AlterField(
            model_name='experienciaslaborale',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/experiencia'),
        ),
        migrations.AlterField(
            model_name='participacioncientifica',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/evento'),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/produccion'),
        ),
        migrations.AlterField(
            model_name='titulosacademico',
            name='cargar_icono',
            field=models.ImageField(blank=True, null=True, upload_to='files/img/imgHome/titulos'),
        ),
    ]
