# Generated by Django 6.0.6 on 2026-07-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0084_produccionacademica_nit_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaslaborale',
            name='nit_empresa',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='nit_empresa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='titulosacademico',
            name='nit_empresa',
            field=models.CharField(max_length=10),
        ),
    ]
