# Generated by Django 6.0.6 on 2026-07-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0085_alter_experienciaslaborale_nit_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescursosimpartidos',
            name='numero_unidad',
            field=models.IntegerField(blank=True),
        ),
    ]
