# Generated by Django 6.0.6 on 2026-07-31 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MisPublicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicaciones_url', models.URLField(blank=True, max_length=300, null=True)),
                ('titulo_publicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_publicacion', models.TextField(blank=True, null=True)),
                ('imagen_publicacion', models.URLField(blank=True, max_length=300, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_video', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
