# Generated by Django 6.0.6 on 2026-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mispublicaciones',
            name='descripcion_publicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mispublicaciones',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mispublicaciones',
            name='imagen_publicacion',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mispublicaciones',
            name='titulo_publicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
