# Generated by Django 6.0.6 on 2026-07-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWeb', '0002_mispublicaciones_descripcion_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mispublicaciones',
            name='id_video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
