
"""
Django settings for proyectoWeb project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from django.conf import settings
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# AWS_ACCESS_KEY_ID="276a3df3955eb2ef6cc5ff5d6bdec0b8"
# AWS_SECRET_ACCESS_KEY="1fb9a30d0b4029a7d9a48a569dce6e4de5a67c2405aa326ad0d959fd1c6615ef"
# HOST="aws-0-us-west-2.pooler.supabase.com"
# NAME="postgres"
# PASSWORD="6Z5gpoBixHlNuwdl"
# PORT="6543"
# SECRET_KEY="django-insecure-pdion^t*fyk8mzv_8a65^oq6nzdz21cot_dzpw#sjlg#auq99w"
# USER="postgres.qxncaqxoiaforsbyjytb"
# SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bmNhcXhvaWFmb3JzYnlqeXRiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTExNjQzNywiZXhwIjoyMDg0NjkyNDM3fQ.UlbiRLeaavpF8c_NM7OV7d1-U51_r-6R9f2RuyulJY"
# SUPABASE_URL="https://qxncaqxoiaforsbyjytb.supabase.co"
# AWS_STORAGE_BUCKET_NAME="media"
# AWS_S3_ENDPOINT_URL="https://qxncaqxoiaforsbyjytb.storage.supabase.co/storage/v1/s3"
# AWS_S3_REGION_NAME="us-west-2"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pdion^t*fyk8mzv_8a65^oq6nzdz21cot_dzpw#sjlg#auq99w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cleanup.apps.CleanupConfig",
    "sorl.thumbnail",
    "storages",
    "physimathcode",
    "autenticacion",
    "hojadevida",
]
# Configuración de los mensajes (esto es opcional, pero es recomendable)
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}



# AWS_ACCESS_KEY_ID = "68aafa97aa82de1281e4e777f591ac97"
# AWS_SECRET_ACCESS_KEY = "405fbd3e10591af04aa845592c8f80ab0a3a4612698c228bc28006c902efa69c"
# SUPABASE_URL = "https://tkkhlfkmsbbbqmdsbhug.supabase.co"
# AWS_STORAGE_BUCKET_NAME = "media"
# AWS_S3_ENDPOINT_URL = "https://tkkhlfkmsbbbqmdsbhug.storage.supabase.co/storage/v1/s3"
# SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsIneyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRra2hsZmttc2JiYnFtZHNiaHVnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDUyMjUxMSwiZXhwIjoyMDg2MDk4NTExfQ.l63eSdms5bL5UVu6ZihCjNITvOApIgFJufIieucPtPw"
# AWS_S3_REGION_NAME = 'us-east-2'

AWS_STORAGE_BUCKET_NAME = os.environ.get("DB_AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.environ.get("DB_AWS_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = os.environ.get("DB_AWS_S3_REGION_NAME")
AWS_ACCESS_KEY_ID = os.environ.get("DB_AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("DB_AWS_SECRET_ACCESS_KEY")
SUPABASE_URL = os.environ.get("DB_SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY =  os.environ.get("DB_SUPABASE_SERVICE_ROLE_KEY") 

AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = "path"
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proyectoWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "physimathcode/plantillas",
              BASE_DIR / "autenticacion/plantillas",
            BASE_DIR / "hojadevida/plantillas",

        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },

]

WSGI_APPLICATION = "proyectoWeb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "db_physimath_mysql",
    #     "USER": "root",
    #     "PASSWORD": "reT@urnSm20Q",
    #     "HOST": "localhost",
    #     "PORT": "3306",
    # }
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }

    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "postgres",
    #     "USER": "postgres.tkkhlfkmsbbbqmdsbhug",
    #     "PASSWORD": "ES1dmwPHkCP3dWIg",
    #     "HOST": "aws-1-us-east-2.pooler.supabase.com",
    #     "PORT": "6543",
    #     "OPTIONS": {"sslmode": "require"},
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("NAME"),
        "USER": os.environ.get("USER"),
        "PASSWORD": os.environ.get("PASSWORD"),
        "HOST": os.environ.get("HOST"),
        "PORT": os.environ.get("PORT"),
        "OPTIONS": {"sslmode": "require"},
        }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [ BASE_DIR / "static",
    # BASE_DIR / "media",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

# MEDIA_URL = "https://qxncaqxoiaforsbyjytb.storage.supabase.co/storage/v1/object/public/media/"
# MEDIA_URL = "https://qxncaqxoiaforsbyjytb.storage.supabase.co/storage/v1/object/public/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# LATEX_GRAPHICSPATH = [
#     os.path.join(
#         settings.BASE_DIR,
#         "media",
#     ),
#     os.path.join(
#         settings.BASE_DIR,
#         "static",
#         "img",
#         "hojadevida",
#     ),
# ]

LATEX_INTERPRETER = "pdflatex"
X_FRAME_OPTIONS = "SAMEORIGIN"

XS_SHARING_ALLOWED_METHODS = ["POST", "GET", "OPTIONS", "PUT", "DELETE"]


